services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: mariadb
      MYSQL_USER: susibel
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:8-apache
    restart: always
    ports:
      - "4080:80"
    environment:
      DB_HOST: db
      DB_USER: susibel

volumes:
  db_data:

